### ISSUE TITLE
Missing binary wheels

### ISSUE THREAD

**Issue by TkTech** [scikit-learn-contrib/hdbscan#525]
The readme claims that the project has binary wheels available, however [looking at PyPi](https://pypi.org/simple/hdbscan/) non-source wheels haven't been built since 0.8.15 for any platform, and 0.8.13 for Linux wheels. Is this an intentional omission? If it's in error, I'd be happy to fix it.

**Comment by lmcinnes** [comment]
Wheel building got broken at some point; I would appreciate it if you
wanted to update the readme.

**Comment by razor-x** [comment]
Any idea what broke? Having wheels for amd64 and arm64 would reduce our build / deploy times by 20-30 minutes. I'd love to help with this.

**Comment by razor-x** [comment]
I built some wheels here: https://github.com/rxfork/hdbscan/releases/tag/0.8.28

If you use poetry you can use them like this

```toml
[[tool.poetry.dependencies.hdbscan]]
python = "^3.9"
markers = "platform_python_implementation == 'CPython' and sys_platform == 'linux' and platform_machine == 'x86_64'"
url = "https://github.com/rxfork/hdbscan/releases/download/0.8.28/hdbscan-0.8.28-cp39-cp39-linux_x86_64.whl"

[[tool.poetry.dependencies.hdbscan]]
python = "^3.9"
markers = "platform_python_implementation == 'CPython' and sys_platform == 'linux' and platform_machine == 'aarch64'"
url = "https://github.com/rxfork/hdbscan/releases/download/0.8.28/hdbscan-0.8.28-cp39-cp39-linux_aarch64.whl"

[[tool.poetry.dependencies.hdbscan]]
version = "0.8.28"

[[tool.poetry.dependencies.hdbscan]]
python = "^3.10"
markers = "platform_python_implementation == 'CPython' and sys_platform == 'linux' and platform_machine == 'x86_64'"
url = "https://github.com/rxfork/hdbscan/releases/download/0.8.28/hdbscan-0.8.28-cp310-cp310-linux_x86_64.whl"

[[tool.poetry.dependencies.hdbscan]]
python = "^3.10"
markers = "platform_python_implementation == 'CPython' and sys_platform == 'linux' and platform_machine == 'aarch64'"
url = "https://github.com/rxfork/hdbscan/releases/download/0.8.28/hdbscan-0.8.28-cp310-cp310-linux_aarch64.whl"
```
